version: '3'

networks:
  open-source-bazaar:

services:
  wiki:
    image: open-source-bazaar/wiki
    networks:
      - open-source-bazaar
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/ || exit 1']
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - 'autoheal=true'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 500M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - open-source-bazaar
    restart: always

  caddy:
    depends_on:
      - wiki
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - open-source-bazaar
    command: caddy reverse-proxy --from your.domain.com --to wiki:3000
